import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryClientProvider from "@/lib/react-query-client-provider";
import NextAuthSessionProvider from "@/lib/session-provider";
import { AuthButton } from "@/components/auth/auth-button";
import { BookOpen } from "lucide-react";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <NextAuthSessionProvider>
        <html lang="en">
          <body
            className={cn(
              `${geistSans.variable} ${geistMono.variable} antialiased`,
              "min-h-screen bg-background"
            )}
          >
            <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-backdrop-filter:bg-background/60">
              <div className="max-w-4xl mx-auto px-4">
                <nav className="flex h-16 items-center justify-between">
                  {/* Logo */}
                  <Link
                    href="/"
                    className="flex items-center gap-2 font-semibold text-lg hover:opacity-80 transition-opacity"
                  >
                    <div className="flex items-center justify-center size-8 rounded-md bg-primary text-primary-foreground">
                      <BookOpen className="size-5" />
                    </div>
                    <span className="hidden sm:inline-block">Blog App</span>
                  </Link>

                  {/* Navigation Links */}
                  <div className="flex items-center gap-1">
                    <AuthButton />
                  </div>
                </nav>
              </div>
            </header>

            <Separator />

            {/* Main Content */}
            <main className="max-w-4xl mx-auto px-4 py-8">
              {children}
            </main>

            {/* Toast Notifications */}
            <Toaster />
          </body>
        </html>
      </NextAuthSessionProvider>
    </ReactQueryClientProvider>
  );
}
